friend_name = "Kirill"
money_count = "300 dollars"
anotherFrienName = "Alexey"
moneyCount = "300 dollars"
cost_car = '600 dolars'
name = "car"
name_car = "car,"
a = "works"
print (friend_name, "и", anotherFrienName, "скинулись на", name, 'со стоимостью в', cost_car, "по", money_count, "=", moneyCount, "для покупки новой", name_car, "для совместной", a)